queries:
  - include: "*"
  - exclude: cpp/short-global-name
  - exclude: py/redundant-global-declaration
extraction:
  cpp:
    prepare:
      packages:
        - python3.8
    index:
      build_command:
        - python3.8 build.py
      vstools_version: 16
  python:
    python_setup:
      version: 3
